const auctionData = [
    {
        id: 1,
        cardName: "Charizard",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "Australia",
        startingPrice: 200,
        currentBid: 210,
        endTime: "10/10/23 12:00:00",
        imageUrl: "/base 2 char.jpeg",
        userId: 'CardCollectorPro',
        verified: true,
        userRating: 4,
        saleType: "Claim Sale",
    },
    {
        id: 2,
        cardName: "Alakazam",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "Australia",
        startingPrice: 200,
        currentBid: 250,
        bidder: "JaneSmith456",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/alakazam.jpeg",
        userId: 'EliteSlabs',
        verified: true,
        userRating: 3,
        saleType: "Claim Sale",
    },
    {
        id: 3,
        cardName: "Blastoise",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "Australia",
        startingPrice: 50,
        currentBid: 75,
        bidder: "MikeJohnson789",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/blastoise.jpeg",
        userId: 'GradeMaster',
        verified: true,
        userRating: 5,
        saleType: "Claim Sale",
    },
    // Additional Cards
    {
        id: 4,
        cardName: "Pikachu",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 8",
        Location: "Japan",
        startingPrice: 100,
        currentBid: 115,
        bidder: "AshKetchum",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/pikachu.jpeg",
        userId: 'PokeTrader',
        verified: true,
        userRating: 4.5,
        saleType: "Claim Sale",
    },
    {
        id: 5,
        cardName: "Venusaur",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "USA",
        startingPrice: 80,
        currentBid: 90,
        bidder: "MistyWater",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/venusaur.jpeg",
        userId: 'CardKingdom',
        verified: true,
        userRating: 4.7,
        saleType: "Claim Sale",
    },
    {
        id: 6,
        cardName: "Mewtwo",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 10",
        Location: "UK",
        startingPrice: 300,
        currentBid: 320,
        bidder: "BrockRocks",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/mewtwo.jpeg",
        userId: 'PokeElite',
        verified: true,
        userRating: 5,
        saleType: "Claim Sale",
    },
    {
        id: 7,
        cardName: "Gyarados",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 8",
        Location: "Canada",
        startingPrice: 70,
        currentBid: 85,
        bidder: "GaryOaks",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/gyarados.jpeg",
        userId: 'SlabMasters',
        verified: true,
        userRating: 4.2,
        saleType: "Claim Sale",
    },
    {
        id: 8,
        cardName: "Machamp",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "Australia",
        startingPrice: 55,
        currentBid: 65,
        bidder: "JessieTeamR",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/machamp.jpeg",
        userId: 'CardHeroes',
        verified: true,
        userRating: 4.8,
        saleType: "Claim Sale",
    },
    {
        id: 9,
        cardName: "Ninetales",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 8",
        Location: "Germany",
        startingPrice: 40,
        currentBid: 50,
        bidder: "JamesTeamR",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/ninetales.jpeg",
        userId: 'PokeLegends',
        verified: true,
        userRating: 4.3,
        saleType: "Claim Sale",
    },
    {
        id: 10,
        cardName: "Zapdos",
        category: "Pokemon",
        set: "Base Set",
        version: "1st Edition",
        Grade: "PSA 9",
        Location: "France",
        startingPrice: 90,
        currentBid: 105,
        bidder: "LtSurge",
        endTime: "10/10/23 12:00:00",
        imageUrl: "/zapdos.jpeg",
        userId: 'PokeMasters',
        verified: true,
        userRating: 4.9,
        saleType: "Claim Sale",
    }
];

export default auctionData;
